---
title: yehwho
timezone: UTC
collections:
  communities:
    title: Communities
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: your-email@domain.com
description: |-
  Lead and develop the Nike West Territory digital vision. Oversee creative development & storytelling that live on Nike West digital and social platforms. Provide strategic direction, partner with key stakeholders, and execute flawlessly.

  Lead and develop the Nike West Territory digital vision. Oversee creative development & storytelling that live on Nike West digital and social platforms. Provide strategic direction, partner with key stakeholders, and execute flawlessly.
baseurl: 
url: http://yourdomain.com
twitter_username: yehwho
pinterest_username: yehwho
instagram_username: yehwho
markdown: kramdown
image: "/uploads/KY-portrait.jpeg"
paragraph: Nike West Coast Digital Director & Formerly @Twitter
