---
title: yehwho
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  about-kam:
    title: about-kam
    output: true
email: your-email@domain.com
description: Nike West Coast Digital Director | Formerly @Twitter
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
image: "/uploads/KY-portrait.jpeg"
